### ISSUE TITLE
Change font-family of footer

### ISSUE THREAD

**Issue by sk0le** [sabesansathananthan/covid-19-tracker#12]
Hi, in footer there is this really ugly text

![img](https://i.ibb.co/ydfxhbv/Screenshot-15.png)

I think with one line of code:
```css
    font-family: "Roboto"; /* Any other nice looking font */
```
You could change it and it would look beautiful.

**Comment by ssat4805** [comment]
Need to change the font family. If you could make a PR @sk0le
